#%RAML 1.0
#api for adding bookings to carts

title: adding bookings

/bookings/addSlots:
  post:
    body:
      application/json:
        example: {
          "user_id": 2,
          "cart_service_id": 37,
          "bookings": [
            {
            "slot_id": 1,
            "booking_time": "5pm",
            "availed": true
            }
          ],
          "bookingDay": "201807044pm"
        }
    responses:
      201:
        body:
          application/json:
            example: {
                "data": {
                  "status": true,
                  "msg": "data successfuly inserted",
                  "cart_total": 10000
                }
            }
