#%RAML 1.0
#api to remove slots from cart

title: get Carts

/bookings/getCart:
  POST:
    body:
      application/json:
        example: {
          "user_id":2,
          }
    responses:
      201:
        body:
          application/json:
            example: {
    "data": {
        "cart_id": 1530690003016,
        "cart_total": 17500,
        "status": true,
        "msg": "cart details found",
        "services": [
            {
                "id": 52,
                "service_id": 1,
                "amount": 9500,
                "count": 0,
                "required_slots": 1,
                "service_name": "Sound Recording",
                "bookings": {
                    "day": "20180704",
                    "timings": [
                        {
                            "service_cart_id": 52,
                            "amount": 5000,
                            "day": "20180704",
                            "booking_time": "5pm"
                        },
                        {
                            "service_cart_id": 52,
                            "amount": 2500,
                            "day": "20180704",
                            "booking_time": "8pm"
                        },
                        {
                            "service_cart_id": 52,
                            "amount": 2000,
                            "day": "20180704",
                            "booking_time": "7pm"
                        }
                    ]
                }
            },
            {
                "id": 53,
                "service_id": 2,
                "amount": 2000,
                "count": 4,
                "required_slots": 0,
                "service_name": "Background Score"
            }
        ]
    }
}
