#%RAML 1.0
#this api is for fetching services user has added to cart

title: Fetch Services  API

/bookings/cartServices:
  post:
    body:
      application/json:
        example: {
          "studio_id":1,
          "user_id":2,
          }
    responses:
      201:
        body:
          application/json:
            example: {

                "data":{
                  "status":false, #(or success)
                  "msg":"Sorry cannot find services",#if success then give success message
                  "services": [
                      {
                          "cart_id": 1530540598108,
                          "total": 8000,
                          "bookings_required": 1,
                          "service_count": 0,
                          "name": "Neelam Studios",
                          "service_name": "Sound Recording",
                          "amount": "3000"
                      },
                      {
                          "cart_id": 1530540598108,
                          "total": 8000,
                          "bookings_required": 0,
                          "service_count": 4,
                          "name": "Neelam Studios",
                          "service_name": "Background Score",
                          "amount": "2000"
                      }
                  ]
              }
