#%RAML 1.0
#this api is for submitting services

title: submitServices API

/submitServices:
  post:
    body:
      application/json:
        example: {
          "studio_id":9,
          "user_id":2,

          "services":[{#if no services are selected then it will be blank
            "service_id":1,
          },
          {
            "service_id":2,
          }],

          }
    responses:
      201:
        body:
          application/json:
            example: {

          "data":{#need to check here that if services are submitted which require slots then that many slots are selected
            "status":"error", #(or success)
            "msg":"Sorry and error has occured.Please try again later.",#if success then give success message
            "cart_total":9000
            }

              }
