#%RAML 1.0
#this api is for fetchinng services on the 1st page

title: Fetch Services  API

/studioServices:
  post:
    body:
      application/json:
        example: {
          "studio_id":9,
          "user_id":2,
          }
    responses:
      201:
        body:
          application/json:
            example: {

                "data":{
                  "status":false, #(or success)
                  "msg":"Sorry Studio Services cannot be found",#if success then give success message
                  "services": [
                          {
                            "studio_service_id": 1,
                            "slots_required": "1",
                            "amount": 3000,
                            "service_name": "Sound Recording"
                          },
                          {
                            "studio_service_id": 2,
                            "slots_required": "0",
                            "amount": 2000,
                            "service_name": "Background Score"
                          }
                      ],
                  }

              }
