#%RAML 1.0
#api to remove slots from cart

title: Uncheck selected slot and remove from cart

/uncheckSlots:
  post:
    body:
      application/json:
        example: {
            "studio_id": 1,
            "user_id": 2,
            "service_id": 2,
            "bookings": [
              {
              "slot_id": 2,
              "booking_time": "2pm",
              "availed": true
              }
            ],
            "bookingDay": "201806302pm"
          }
    responses:
      201:
        body:
          application/json:
            example: {
                "data": {
                  "status": true,
                  "msg": "slot successfuly removed",
                  "cart_id": 1530112911254
                }
            }
