#%RAML 1.0
#this api is for submitting services

title: submitServices API

/submitServices:
  post:
    body:
      application/json:
        example: {
          "studio_id":9,
          "user_id":2,

          "services":[{#if no services are selected then it will be blank
            "service_id":1,
            "count":0,#it is 0 as this service requires slots, and CAN'T be increased by itself
          },
          {
            "service_id":2,
            "count":4,#it is 4 as this service does not require slots, and CAN be increased by itself
          }],

          }
    responses:
      201:
        body:
          application/json:
            example: {

          "data":{
            "status":false, #(or success)
            "msg":"Sorry and error has occured.Please try again later.",#if success then give success message
            "cart_total":9000
            }

              }
