#%RAML 1.0
#api to remove slots from cart

title: Uncheck selected slot and remove from cart

/bookings/uncheckSlots:
  post:
    body:
      application/json:
        example: {
            "user_id": 2,
            "cart_service_id": 37,
            "bookings": [
              {
              "slot_id": 1,
              "booking_time": "5pm",
              "availed": true
              }
            ],
            "bookingDay": "201807044pm"
          }
    responses:
      201:
        body:
          application/json:
            example: {
                "data": {
                  "status": true,
                  "msg": "slot successfuly removed",
                  "cart_total": 10000
                }
            }
