#%RAML 1.0
#this api is called when user clicks on Book Studio of Studio Page

title: BookingsFetch API

/bookings?studioid=123:
  get:
    responses:
      200:
        body:
          application/json:
            example:
              {
  "data": {
    "studio_id": 1,
    "studio_name": "Neelam Studios",
    "services": [
      {
        "studio_service_id": 1,
        "slots_required": "1",
        "amount": 3000,
        "service_name": "Sound Recording"
      },
      {
        "studio_service_id": 2,
        "slots_required": "0",
        "amount": 2000,
        "service_name": "Background Score"
      }
    ],
    "bookings": [
      {
        "slotId": 3,
        "studioId": 1,
        "date": "20180622",
        "timings": [
          {
            "hour": "8am",
            "amount": "1000",
            "booked": true
          },
          {
            "hour": "9am",
            "amount": "1000",
            "booked": false
          },
          {
            "hour": "10am",
            "amount": "1000",
            "booked": true
          },
          {
            "hour": "11am",
            "amount": "1000",
            "booked": false
          },
          {
            "hour": "12pm",
            "amount": "1000",
            "booked": false
          },
          {
            "hour": "1pm",
            "amount": "1000",
            "booked": false
          },
          {
            "hour": "2pm",
            "amount": "1000",
            "booked": false
          },
          {
            "hour": "3pm",
            "amount": "1000",
            "booked": false
          },
          {
            "hour": "4pm",
            "amount": "1000",
            "booked": false
          },
          {
            "hour": "5pm",
            "amount": "1000",
            "booked": false
          },
          {
            "hour": "6pm",
            "amount": "1000",
            "booked": false
          },
          {
            "hour": "7pm",
            "amount": "1000",
            "booked": false
          },
          {
            "hour": "8pm",
            "amount": "2000",
            "booked": false
          },
          {
            "hour": "9pm",
            "amount": "2500",
            "booked": false
          },
          {
            "hour": "10pm",
            "amount": "3000",
            "booked": false
          },
          {
            "hour": "11pm",
            "amount": "1000",
            "booked": false
          },
          {
            "hour": "12am",
            "amount": "1000",
            "booked": false
          },
          {
            "hour": "1am",
            "amount": "1000",
            "booked": false
          },
          {
            "hour": "2am",
            "amount": "1000",
            "booked": false
          },
          {
            "hour": "3am",
            "amount": "4000",
            "booked": false
          },
          {
            "hour": "4am",
            "amount": "4000",
            "booked": false
          },
          {
            "hour": "5am",
            "amount": "1000",
            "booked": false
          },
          {
            "hour": "6am",
            "amount": "4000",
            "booked": false
          },
          {
            "hour": "7am",
            "amount": "4000",
            "booked": false
          }
        ]
      }
    ]
  }
}
